# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog, QScrollArea, QWidget, QVBoxLayout, QHBoxLayout, QLabel
from PyQt6.QtCore import QObject, pyqtSignal
import json
from PyQt6.QtCore import QProcess, pyqtSignal, QThread
import threading


# Signal emitter for thread-safe GUI updates
class LogEmitter(QObject):
    log_signal = pyqtSignal(str)


class Ui_MainWindow(object):
    def load_json(self):
        try: 
            with open('Model.json', "r") as f:
                return json.load(f)
        except Exception as e:
            print(f"ERROR loading Model.json: {e}")
            return {}

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 660)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 0, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tab_box = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_box.setGeometry(QtCore.QRect(10, 50, 881, 561))
        self.tab_box.setObjectName("tab_box")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 481, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sav_text = QtWidgets.QLineEdit(parent=self.groupBox)
        self.sav_text.setGeometry(QtCore.QRect(100, 40, 321, 21))
        self.sav_text.setObjectName("sav_text")
        self.sav_text.setText("D:\Trung-alone\DAKS\intern\De_a_TUAN_ANH\STEP_TRUNG\Gen_293210_1_OFF.sav")
        font.setPointSize(8)
        self.sav_text.setFont(font)
        self.sav = QtWidgets.QPushButton(parent=self.groupBox)
        self.sav.setGeometry(QtCore.QRect(430, 40, 41, 21))
        self.sav.setObjectName("sav")
        self.sav.clicked.connect(self.select_sav_file) # click ... de tim pathh file sav
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dyr_text = QtWidgets.QLineEdit(parent=self.groupBox)
        self.dyr_text.setGeometry(QtCore.QRect(100, 80, 321, 21))
        self.dyr_text.setObjectName("dyr_text")
        self.dyr_text.setText("D:\Trung-alone\DAKS\intern\De_a_TUAN_ANH\STEP_TRUNG\OFF.dyr")
        font.setPointSize(8)
        self.dyr_text.setFont(font)
        self.dyr = QtWidgets.QPushButton(parent=self.groupBox)
        self.dyr.setGeometry(QtCore.QRect(430, 80, 41, 21))
        self.dyr.setObjectName("dyr")
        self.dyr.clicked.connect(self.select_dyr_file) # click ... de tim pathh file dyr
        self.label_27 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(20, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.out_text = QtWidgets.QLineEdit(parent=self.groupBox)
        self.out_text.setGeometry(QtCore.QRect(100, 120, 321, 21))
        self.out_text.setObjectName("out_file")
        self.out_text.setText("D:\Trung-alone\DAKS\intern\De_a_TUAN_ANH\STEP_TRUNG\GUI.out")
        font.setPointSize(8)
        self.out_text.setFont(font)
        self.out = QtWidgets.QPushButton(parent=self.groupBox)
        self.out.setGeometry(QtCore.QRect(430, 120, 41, 21))
        self.out.setObjectName("out")
        self.out.clicked.connect(self.select_out_file) # click ... de tim pathh file out
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 481, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")


        self.log_output = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.log_output.setGeometry(QtCore.QRect(5, 25, 470, 215))
        self.log_output.setReadOnly(True)
        self.log_output.setObjectName("log_output")
        font_log = QtGui.QFont()
        font_log.setFamily("Courier New")
        font_log.setPointSize(9)
        self.log_output.setFont(font_log)

        self.run = QtWidgets.QPushButton(parent=self.tab)
        self.run.setGeometry(QtCore.QRect(570, 100, 93, 28))
        self.run.setObjectName("run")
        self.run.clicked.connect(self.run_py)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 190, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.cancel = QtWidgets.QPushButton(parent=self.tab)
        self.cancel.setGeometry(QtCore.QRect(570, 290, 93, 28))
        self.cancel.setObjectName("cancel")
        self.cancel.clicked.connect(self.stop)
        self.tab_box.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 351, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 150, 351, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 55, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(220, 30, 55, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(220, 100, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Bus_id = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.Bus_id.setGeometry(QtCore.QRect(70, 30, 113, 22))
        self.Bus_id.setObjectName("Bus_id")
        self.Bus_id.setText("293210")
        self.gen_id = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.gen_id.setGeometry(QtCore.QRect(240, 30, 81, 21))
        self.gen_id.setObjectName("gen_id")
        self.gen_id.setText("1")
        self.simulation_time = QtWidgets.QSpinBox(parent=self.groupBox_3)
        self.simulation_time.setGeometry(QtCore.QRect(120, 60, 42, 22))
        self.simulation_time.setObjectName("simulation_time")
        self.simulation_time.setValue(10)
        self.time_fault = QtWidgets.QSpinBox(parent=self.groupBox_3)
        self.time_fault.setGeometry(QtCore.QRect(120, 100, 42, 22))
        self.time_fault.setObjectName("time_fault")
        self.time_fault.setValue(2)
        self.step_fault = QtWidgets.QSpinBox(parent=self.groupBox_3)
        self.step_fault.setGeometry(QtCore.QRect(290, 100, 42, 22))
        self.step_fault.setObjectName("step_fault")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 200, 491, 241))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox_5)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 141, 21))
        self.checkBox.setObjectName("checkBox")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 80, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(200, 80, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(20, 160, 55, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(200, 160, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.iteration = QtWidgets.QSpinBox(parent=self.groupBox_5)
        self.iteration.setGeometry(QtCore.QRect(90, 80, 42, 22))
        self.iteration.setObjectName("iteration")
        self.iteration.setValue(25)
        self.tolerance = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.tolerance.setGeometry(QtCore.QRect(290, 80, 91, 21))
        self.tolerance.setObjectName("tolerance")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.groupBox_5)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 130, 171, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.DELT = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.DELT.setGeometry(QtCore.QRect(60, 160, 113, 22))
        self.DELT.setObjectName("DELT")
        self.DELT.setText("0.01")
        self.freq = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.freq.setGeometry(QtCore.QRect(270, 160, 113, 22))
        self.freq.setObjectName("freq")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(390, 20, 361, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.groupBox_6)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 30, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(160, 40, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.spinBox_5 = QtWidgets.QSpinBox(parent=self.groupBox_7)
        self.spinBox_5.setGeometry(QtCore.QRect(20, 30, 42, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(parent=self.groupBox_7)
        self.spinBox_6.setGeometry(QtCore.QRect(20, 60, 42, 22))
        self.spinBox_6.setObjectName("spinBox_6")
        self.groupBox_9 = QtWidgets.QGroupBox(parent=self.groupBox_6)
        self.groupBox_9.setGeometry(QtCore.QRect(260, 40, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.spinBox_7 = QtWidgets.QSpinBox(parent=self.groupBox_9)
        self.spinBox_7.setGeometry(QtCore.QRect(20, 30, 42, 22))
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_8 = QtWidgets.QSpinBox(parent=self.groupBox_9)
        self.spinBox_8.setGeometry(QtCore.QRect(20, 60, 42, 22))
        self.spinBox_8.setObjectName("spinBox_8")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(20, 70, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(20, 100, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.tab_box.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.PSO_box = QtWidgets.QGroupBox(parent=self.tab_4)
        self.PSO_box.setGeometry(QtCore.QRect(20, 20, 271, 301))
        self.PSO_box.setObjectName("PSO_box")
        self.label_11 = QtWidgets.QLabel(parent=self.PSO_box)
        self.label_11.setGeometry(QtCore.QRect(50, 40, 91, 21))
        self.label_11.setObjectName("label_11")
        self.iteration_2 = QtWidgets.QSpinBox(parent=self.PSO_box)
        self.iteration_2.setGeometry(QtCore.QRect(180, 40, 60, 22))
        self.iteration_2.setObjectName("iteration_2")
        self.iteration_2.setMaximum(9999)
        self.iteration_2.setValue(25)
        self.label_19 = QtWidgets.QLabel(parent=self.PSO_box)
        self.label_19.setGeometry(QtCore.QRect(50, 90, 81, 16))
        self.label_19.setObjectName("label_19")
        self.particle = QtWidgets.QSpinBox(parent=self.PSO_box)
        self.particle.setGeometry(QtCore.QRect(180, 90, 65, 22))
        self.particle.setObjectName("particle")
        self.particle.setMaximum(1000)
        self.particle.setValue(10)
        self.label_20 = QtWidgets.QLabel(parent=self.PSO_box)
        self.label_20.setGeometry(QtCore.QRect(60, 140, 55, 16))
        self.label_20.setObjectName("label_20")
        self.c1 = QtWidgets.QDoubleSpinBox(parent=self.PSO_box)
        self.c1.setGeometry(QtCore.QRect(180, 140, 62, 22))
        self.c1.setObjectName("c1")
        self.c1.setValue(2.00)
        self.label_21 = QtWidgets.QLabel(parent=self.PSO_box)
        self.label_21.setGeometry(QtCore.QRect(60, 180, 55, 16))
        self.label_21.setObjectName("label_21")
        self.c2 = QtWidgets.QDoubleSpinBox(parent=self.PSO_box)
        self.c2.setGeometry(QtCore.QRect(180, 180, 62, 22))
        self.c2.setObjectName("c2")
        self.c2.setValue(2.00)
        self.label_22 = QtWidgets.QLabel(parent=self.PSO_box)
        self.label_22.setGeometry(QtCore.QRect(60, 220, 55, 16))
        self.label_22.setObjectName("label_22")
        self.wmax = QtWidgets.QDoubleSpinBox(parent=self.PSO_box)
        self.wmax.setGeometry(QtCore.QRect(180, 220, 62, 22))
        self.wmax.setObjectName("wmax")
        self.wmax.setValue(1.40)
        self.label_28 = QtWidgets.QLabel(parent=self.PSO_box)
        self.label_28.setGeometry(QtCore.QRect(60, 260, 55, 16))
        self.label_28.setObjectName("label_28")
        self.wmin = QtWidgets.QDoubleSpinBox(parent=self.PSO_box)
        self.wmin.setGeometry(QtCore.QRect(180, 260, 62, 22))
        self.wmin.setObjectName("wmin")
        self.wmin.setValue(0.40)
        self.REF_box = QtWidgets.QGroupBox(parent=self.tab_4)
        self.REF_box.setGeometry(QtCore.QRect(310, 20, 531, 301))
        self.REF_box.setObjectName("REF_box")
        self.ref = QtWidgets.QPushButton(parent=self.REF_box)
        self.ref.setGeometry(QtCore.QRect(430, 40, 41, 21))
        self.ref.setObjectName("ref")
        
        self.ref.clicked.connect(self.select_ref_file) # click ... de tim pathh file ref
        self.label_9 = QtWidgets.QLabel(parent=self.REF_box)
        self.label_9.setGeometry(QtCore.QRect(150, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")


        self.label_10 = QtWidgets.QLabel(parent=self.REF_box)
        self.label_10.setGeometry(QtCore.QRect(40, 115, 55, 20))
        self.label_10.setObjectName("label_10")
        self.ref_check_P = QtWidgets.QCheckBox(parent=self.REF_box)
        self.ref_check_P.setGeometry(QtCore.QRect(100, 115, 50, 20))
        self.ref_check_P.setObjectName("ref_check_P")
        self.ref_check_Q = QtWidgets.QCheckBox(parent=self.REF_box)
        self.ref_check_Q.setGeometry(QtCore.QRect(160, 115, 50, 20))
        self.ref_check_Q.setObjectName("ref_check_Q")
        self.ref_check_Vt = QtWidgets.QCheckBox(parent=self.REF_box)
        self.ref_check_Vt.setGeometry(QtCore.QRect(220, 115, 50, 20))
        self.ref_check_Vt.setObjectName("ref_check_Vt")
        self.ref_check_Ef = QtWidgets.QCheckBox(parent=self.REF_box)
        self.ref_check_Ef.setGeometry(QtCore.QRect(280, 115, 50, 20))
        self.ref_check_Ef.setObjectName("ref_check_Ef")
        self.ref_check_If = QtWidgets.QCheckBox(parent=self.REF_box)
        self.ref_check_If.setGeometry(QtCore.QRect(340, 115, 50, 20))
        self.ref_check_If.setObjectName("ref_check_If")

        # self.label_10.setGeometry(QtCore.QRect(40, 120, 55, 16))
        # self.label_10.setObjectName("label_10")
        self.ref_text = QtWidgets.QLineEdit(parent=self.REF_box)
        self.ref_text.setGeometry(QtCore.QRect(100, 40, 321, 21))
        self.ref_text.setObjectName("ref_text")
        self.ref_text.setText("D:\Trung-alone\DAKS\intern\De_a_TUAN_ANH\STEP_TRUNG\input_test.csv")
        font.setPointSize(8)
        self.ref_text.setFont(font)
        self.label_8 = QtWidgets.QLabel(parent=self.REF_box)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_43 = QtWidgets.QLabel(parent=self.REF_box)
        self.label_43.setGeometry(QtCore.QRect(40, 170, 81, 16))
        self.label_43.setObjectName("label_43")
        self.disturbance = QtWidgets.QComboBox(parent=self.REF_box)
        self.disturbance.setGeometry(QtCore.QRect(140, 170, 73, 22))
        self.disturbance.setObjectName("disturbance")
        self.disturbance.addItem("")
        self.disturbance.addItem("")
        self.disturbance.addItem("")
        self.tab_box.addTab(self.tab_4, "")
        self.tab_Gen = QtWidgets.QWidget()
        self.tab_Gen.setObjectName("tab_Gen")
        self.GEN_check = QtWidgets.QCheckBox(parent=self.tab_Gen)
        self.GEN_check.setGeometry(QtCore.QRect(70, 50, 81, 20))
        self.GEN_check.setObjectName("GEN_check")
        self.GEN_check.stateChanged.connect(self.on_GEN_check_changed) # thay doi
        self.label_23 = QtWidgets.QLabel(parent=self.tab_Gen)
        self.label_23.setGeometry(QtCore.QRect(250, 0, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.GEN_list = QtWidgets.QComboBox(parent=self.tab_Gen)
        self.GEN_list.setGeometry(QtCore.QRect(150, 90, 73, 22))
        self.GEN_list.setObjectName("GEN_list")
        self.GEN_list.addItem("")
        self.GEN_list.addItem("")
        self.GEN_list.currentTextChanged.connect(self.on_GEN_model_changed) # Thay doi
        self.GEN_label = QtWidgets.QLabel(parent=self.tab_Gen)
        self.GEN_label.setGeometry(QtCore.QRect(70, 90, 81, 16))
        self.GEN_label.setObjectName("GEN_label")
        self.groupBox_8 = QtWidgets.QGroupBox(parent=self.tab_Gen)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 110, 851, 411))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.roll_GEN = QtWidgets.QScrollBar(parent=self.groupBox_8)
        self.roll_GEN.setGeometry(QtCore.QRect(790, 20, 21, 541))
        self.roll_GEN.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.roll_GEN.setObjectName("roll_GEN")

        # Scroll area for GEN parameters
        self.scroll_GEN = QScrollArea(parent=self.groupBox_8)
        self.scroll_GEN.setGeometry(QtCore.QRect(10, 20, 770, 390))
        self.scroll_GEN.setWidgetResizable(True)
        self.scroll_GEN.setObjectName("scroll_GEN")

        # Container widget for GEN parameters
        self.scroll_GEN_widget = QWidget()
        self.scroll_GEN.setWidget(self.scroll_GEN_widget)
        self.scroll_GEN_layout = QVBoxLayout(self.scroll_GEN_widget)
        self.scroll_GEN_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)

        # Initially hide GEN_list and scroll area
        self.GEN_list.hide()
        self.GEN_label.hide()
        self.groupBox_8.hide()
        self.scroll_GEN.hide()
        

        # Store GEN parameter checkboxes and scrollbars
        self.GEN_param_widgets = {}

        # Select All button for GEN
        self.GEN_select_all = QtWidgets.QPushButton(parent=self.tab_Gen)
        self.GEN_select_all.setGeometry(QtCore.QRect(750, 50, 90, 25))
        self.GEN_select_all.setObjectName("GEN_select_all")
        self.GEN_select_all.setText("Select All")
        self.GEN_select_all.clicked.connect(self.on_GEN_select_all)
        self.GEN_select_all.hide()


        self.tab_box.addTab(self.tab_Gen, "")
        self.tab_AVR = QtWidgets.QWidget()
        self.tab_AVR.setObjectName("tab_AVR")
        self.label_29 = QtWidgets.QLabel(parent=self.tab_AVR)
        self.label_29.setGeometry(QtCore.QRect(300, 0, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.AVR_label = QtWidgets.QLabel(parent=self.tab_AVR)
        self.AVR_label.setGeometry(QtCore.QRect(80, 90, 81, 16))
        self.AVR_label.setObjectName("AVR_label")
        self.groupBox_10 = QtWidgets.QGroupBox(parent=self.tab_AVR)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 110, 851, 411))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.AVR_check = QtWidgets.QCheckBox(parent=self.tab_AVR)
        self.AVR_check.setGeometry(QtCore.QRect(80, 50, 81, 20))
        self.AVR_check.setObjectName("AVR_check")
        self.AVR_list = QtWidgets.QComboBox(parent=self.tab_AVR)
        self.AVR_list.setGeometry(QtCore.QRect(160, 90, 73, 22))
        self.AVR_list.setObjectName("AVR_list")
        self.AVR_list.addItem("")
        self.AVR_list.addItem("")
        self.AVR_list.addItem("")

        self.AVR_check.stateChanged.connect(self.on_AVR_check_changed)
        self.AVR_list.currentTextChanged.connect(self.on_AVR_model_changed)
        self.roll_AVR = QtWidgets.QScrollBar(parent=self.groupBox_10)
        self.roll_AVR.setGeometry(QtCore.QRect(790, 20, 21, 541))
        self.roll_AVR.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.roll_AVR.setObjectName("roll_AVR")
        self.scroll_AVR = QScrollArea(parent=self.groupBox_10)
        self.scroll_AVR.setGeometry(QtCore.QRect(10, 20, 770, 390))
        self.scroll_AVR.setWidgetResizable(True)
        self.scroll_AVR.setObjectName("scroll_GEN")
        self.scroll_AVR_widget = QWidget()
        self.scroll_AVR.setWidget(self.scroll_AVR_widget)
        self.scroll_AVR_layout = QVBoxLayout(self.scroll_AVR_widget)
        self.scroll_AVR_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.AVR_list.hide()
        self.AVR_label.hide()
        self.groupBox_10.hide()
        self.scroll_AVR.hide()
        self.AVR_param_widgets = {}

        # Select All button for AVR
        self.AVR_select_all = QtWidgets.QPushButton(parent=self.tab_AVR)
        self.AVR_select_all.setGeometry(QtCore.QRect(750, 50, 90, 25))
        self.AVR_select_all.setObjectName("AVR_select_all")
        self.AVR_select_all.setText("Select All")
        self.AVR_select_all.clicked.connect(self.on_AVR_select_all)
        self.AVR_select_all.hide()

        self.tab_box.addTab(self.tab_AVR, "")
        self.tab_GOV = QtWidgets.QWidget()
        self.tab_GOV.setObjectName("tab_GOV")
        self.GOV_list = QtWidgets.QComboBox(parent=self.tab_GOV)
        self.GOV_list.setGeometry(QtCore.QRect(160, 90, 73, 22))
        self.GOV_list.setObjectName("GOV_list")
        self.GOV_list.addItem("")
        self.GOV_check = QtWidgets.QCheckBox(parent=self.tab_GOV)
        self.GOV_check.setGeometry(QtCore.QRect(80, 50, 81, 20))
        self.GOV_check.setObjectName("GOV_check")
        self.GOV_label = QtWidgets.QLabel(parent=self.tab_GOV)
        self.GOV_label.setGeometry(QtCore.QRect(80, 90, 81, 16))
        self.GOV_label.setObjectName("GOV_label")
        self.groupBox_11 = QtWidgets.QGroupBox(parent=self.tab_GOV)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 110, 851, 411))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")


        self.GOV_check.stateChanged.connect(self.on_GOV_check_changed)
        self.GOV_list.currentTextChanged.connect(self.on_GOV_model_changed)
        self.roll_GOV = QtWidgets.QScrollBar(parent=self.groupBox_11)
        self.roll_GOV.setGeometry(QtCore.QRect(790, 20, 21, 541))
        self.roll_GOV.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.roll_GOV.setObjectName("roll_GOV")
        self.scroll_GOV = QScrollArea(parent=self.groupBox_11)
        self.scroll_GOV.setGeometry(QtCore.QRect(10, 20, 770, 390))
        self.scroll_GOV.setWidgetResizable(True)
        self.scroll_GOV.setObjectName("scroll_GOV")
        self.scroll_GOV_widget = QWidget()
        self.scroll_GOV.setWidget(self.scroll_GOV_widget)
        self.scroll_GOV_layout = QVBoxLayout(self.scroll_GOV_widget)
        self.scroll_GOV_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.GOV_list.hide()
        self.GOV_label.hide()
        self.groupBox_11.hide()
        self.scroll_GOV.hide()
        self.GOV_param_widgets = {}

        # Select All button for GOV
        self.GOV_select_all = QtWidgets.QPushButton(parent=self.tab_GOV)
        self.GOV_select_all.setGeometry(QtCore.QRect(750, 50, 90, 25))
        self.GOV_select_all.setObjectName("GOV_select_all")
        self.GOV_select_all.setText("Select All")
        self.GOV_select_all.clicked.connect(self.on_GOV_select_all)
        self.GOV_select_all.hide()


        self.label_38 = QtWidgets.QLabel(parent=self.tab_GOV)
        self.label_38.setGeometry(QtCore.QRect(280, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.tab_box.addTab(self.tab_GOV, "")
        self.tab_PSS = QtWidgets.QWidget()
        self.tab_PSS.setObjectName("tab_PSS")
        self.label_39 = QtWidgets.QLabel(parent=self.tab_PSS)
        self.label_39.setGeometry(QtCore.QRect(300, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.PSS_label = QtWidgets.QLabel(parent=self.tab_PSS)
        self.PSS_label.setGeometry(QtCore.QRect(80, 90, 81, 16))
        self.PSS_label.setObjectName("PSS_label")
        self.groupBox_13 = QtWidgets.QGroupBox(parent=self.tab_PSS)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 110, 851, 411))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.PSS_check = QtWidgets.QCheckBox(parent=self.tab_PSS)
        self.PSS_check.setGeometry(QtCore.QRect(80, 50, 81, 20))
        self.PSS_check.setObjectName("PSS_check")
        self.PSS_list = QtWidgets.QComboBox(parent=self.tab_PSS)
        self.PSS_list.setGeometry(QtCore.QRect(160, 90, 73, 22))
        self.PSS_list.setObjectName("PSS_list")
        self.PSS_list.addItem("")

        self.PSS_check.stateChanged.connect(self.on_PSS_check_changed)
        self.PSS_list.currentTextChanged.connect(self.on_PSS_model_changed)
        self.roll_PSS = QtWidgets.QScrollBar(parent=self.groupBox_13)
        self.roll_PSS.setGeometry(QtCore.QRect(790, 20, 21, 541))
        self.roll_PSS.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.roll_PSS.setObjectName("roll_PSS")
        self.scroll_PSS = QScrollArea(parent=self.groupBox_13)
        self.scroll_PSS.setGeometry(QtCore.QRect(10, 20, 770, 390))
        self.scroll_PSS.setWidgetResizable(True)
        self.scroll_PSS.setObjectName("scroll_PSS")
        self.scroll_PSS_widget = QWidget()
        self.scroll_PSS.setWidget(self.scroll_PSS_widget)
        self.scroll_PSS_layout = QVBoxLayout(self.scroll_PSS_widget)
        self.scroll_PSS_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.PSS_list.hide()
        self.PSS_label.hide()
        self.groupBox_13.hide()
        self.scroll_PSS.hide()
        self.PSS_param_widgets = {}

        # Select All button for PSS
        self.PSS_select_all = QtWidgets.QPushButton(parent=self.tab_PSS)
        self.PSS_select_all.setGeometry(QtCore.QRect(750, 50, 90, 25))
        self.PSS_select_all.setObjectName("PSS_select_all")
        self.PSS_select_all.setText("Select All")
        self.PSS_select_all.clicked.connect(self.on_PSS_select_all)
        self.PSS_select_all.hide()


        self.tab_box.addTab(self.tab_PSS, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # self.process = QProcess()
        # self.process.readyReadStandardOutput.connect(self.handle_stdout)
        # self.process.readyReadStandardError.connect(self.handle_stderr)
        # self.process.finished.connect(self.process_finished)
    def select_sav_file(self):
        file_path, _ = QFileDialog.getOpenFileName(
            None,
            "Select file .sav",
            "",
            "SAV Files (*.sav);;ALL Files (*)"
        )
        if file_path:
            self.sav_text.setText(file_path)
    def select_dyr_file(self):
        file_path, _ = QFileDialog.getOpenFileName(
            None,
            "Select file .dyr",
            "",
            "DYR Files (*.dyr);;ALL Files (*)"
        )
        if file_path:
            self.dyr_text.setText(file_path)
    def select_out_file(self):
        file_path, _ = QFileDialog.getOpenFileName(
            None,
            "Select file .out",
            "",
            "OUT Files (*.out);;ALL Files (*)"
        )
        if file_path:
            self.out_text.setText(file_path)

    def select_ref_file(self):
        file_path, _ = QFileDialog.getOpenFileName(
            None,
            "Select file .csv, .xlsx",
            "",
            "REF Files (*.csv, *.xlsx);;ALL Files (*)"
        )
        if file_path:
            self.ref_text.setText(file_path)

    def on_GEN_check_changed(self, state):
        if state == QtCore.Qt.CheckState.Checked.value:
            self.GEN_list.show()
            self.GEN_label.show()
            self.GEN_select_all.show()
            current_model = self.GEN_list.currentText()
            if current_model:
                self.on_GEN_model_changed(current_model)
        else:
            self.GEN_list.hide()
            self.GEN_label.hide()
            self.GEN_select_all.hide()
            self.groupBox_8.hide()
            self.scroll_GEN.hide()
            

    def on_GEN_model_changed(self, model_name):
        while self.scroll_GEN_layout.count():
            item = self.scroll_GEN_layout.takeAt(0)
            widget = item.widget()
            if widget:
                widget.setParent(None)
        self.GEN_param_widgets = {}

        if not self.GEN_check.isChecked() or not model_name or model_name == "":
            self.groupBox_8.hide()
            self.scroll_GEN.hide()
            return
        
        model_data = self.load_json()
        gen_models = model_data.get('Model_dynamic', {}).get('GEN', {})

        if model_name in gen_models:
            params = gen_models[model_name]
            if params:
                self.groupBox_8.show()
                self.scroll_GEN.show()

                grid_widget = QWidget()
                grid_layout = QtWidgets.QGridLayout(grid_widget)
                grid_layout.setContentsMargins(10, 5, 10, 5)
                grid_layout.setHorizontalSpacing(8)
                grid_layout.setVerticalSpacing(4)

                header_default = QLabel("Default")
                header_default.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                header_range = QLabel("Range")
                header_range.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                grid_layout.addWidget(header_default, 0, 1)
                grid_layout.addWidget(header_range,   0, 2, 1, 3)
                for row_idx, (param_name, param_values) in enumerate(params.items(), start=1):
                    initial = param_values.get('initial', 0)
                    lb      = param_values.get('lb', 0)
                    ub      = param_values.get('ub', 100)
                    idx     = param_values.get('idx', 0)

                    param_checkbox = QtWidgets.QCheckBox(param_name)
                    param_checkbox.setObjectName(f"GEN_{model_name}_{param_name}")
                    # col 1: init (Default)
                    init_edit = QtWidgets.QLineEdit(f"{initial:.4f}")
                    init_edit.setFixedWidth(75)
                    init_edit.setObjectName(f"GEN_{model_name}_{param_name}_init")

                    # col 2: min (Range từ)
                    min_edit = QtWidgets.QLineEdit(f"{lb:.4f}")
                    min_edit.setFixedWidth(75)
                    min_edit.setObjectName(f"GEN_{model_name}_{param_name}_min")

                    # col 3: dấu gạch ngang giữa min-max
                    dash_label = QLabel("-")
                    dash_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

                    # col 4: max (Range đến)
                    max_edit = QtWidgets.QLineEdit(f"{ub:.4f}")
                    max_edit.setFixedWidth(75)
                    max_edit.setObjectName(f"GEN_{model_name}_{param_name}_max")

                    # Ẩn init/min/max sẵn, chỉ hiện khi tích checkbox
                    init_edit.hide()
                    min_edit.hide()
                    dash_label.hide()
                    max_edit.hide()

                    grid_layout.addWidget(param_checkbox, row_idx, 0)
                    grid_layout.addWidget(init_edit,      row_idx, 1)
                    grid_layout.addWidget(min_edit,       row_idx, 2)
                    grid_layout.addWidget(dash_label,     row_idx, 3)
                    grid_layout.addWidget(max_edit,       row_idx, 4)
                    # Connect checkbox: tích mới hiện Default và Range fields
                    param_checkbox.stateChanged.connect(
                        lambda state, ie=init_edit, mne=min_edit, dl=dash_label, mxe=max_edit:
                        [w.setVisible(state == QtCore.Qt.CheckState.Checked.value)
                         for w in (ie, mne, dl, mxe)]
                    )
                    # Store references
                    self.GEN_param_widgets[param_name] = {
                        'checkbox':  param_checkbox,
                        'initial':   initial,
                        'min':       lb,
                        'max':       ub,
                        'init_edit': init_edit,
                        'min_edit':  min_edit,
                        'max_edit':  max_edit,
                        'idx': idx
                    }

                self.scroll_GEN_layout.addWidget(grid_widget)
            else:
                self.scroll_GEN.hide()
                self.groupBox_8.hide()
        else:
            self.scroll_GEN.hide()
            self.groupBox_8.hide()
    def on_AVR_check_changed(self, state):
            if state == QtCore.Qt.CheckState.Checked.value:
                self.AVR_list.show()
                self.AVR_label.show()
                self.AVR_select_all.show()
                current_model = self.AVR_list.currentText()
                if current_model:
                    self.on_AVR_model_changed(current_model)
            else:
                self.AVR_list.hide()
                self.AVR_label.hide()
                self.AVR_select_all.hide()
                self.groupBox_10.hide()
                self.scroll_AVR.hide()
                

    def on_AVR_model_changed(self, model_name):
            while self.scroll_AVR_layout.count():
                item = self.scroll_AVR_layout.takeAt(0)
                widget = item.widget()
                if widget:
                    widget.setParent(None)
            self.AVR_param_widgets = {}

            if not self.AVR_check.isChecked() or not model_name or model_name == "":
                self.groupBox_10.hide()
                self.scroll_AVR.hide()
                return
            
            model_data = self.load_json()
            gen_models = model_data.get('Model_dynamic', {}).get('AVR', {})

            if model_name in gen_models:
                params = gen_models[model_name]
                if params:
                    self.groupBox_10.show()
                    self.scroll_AVR.show()

                    grid_widget = QWidget()
                    grid_layout = QtWidgets.QGridLayout(grid_widget)
                    grid_layout.setContentsMargins(10, 5, 10, 5)
                    grid_layout.setHorizontalSpacing(8)
                    grid_layout.setVerticalSpacing(4)

                    header_default = QLabel("Default")
                    header_default.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                    header_range = QLabel("Range")
                    header_range.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                    grid_layout.addWidget(header_default, 0, 1)
                    grid_layout.addWidget(header_range,   0, 2, 1, 3)
                    for row_idx, (param_name, param_values) in enumerate(params.items(), start=1):
                        initial = param_values.get('initial', 0)
                        lb      = param_values.get('lb', 0)
                        ub      = param_values.get('ub', 100)
                        idx     = param_values.get('idx', 0)

                        param_checkbox = QtWidgets.QCheckBox(param_name)
                        param_checkbox.setObjectName(f"AVR_{model_name}_{param_name}")
                        # col 1: init (Default)
                        init_edit = QtWidgets.QLineEdit(f"{initial:.4f}")
                        init_edit.setFixedWidth(75)
                        init_edit.setObjectName(f"AVR_{model_name}_{param_name}_init")

                        # col 2: min (Range từ)
                        min_edit = QtWidgets.QLineEdit(f"{lb:.4f}")
                        min_edit.setFixedWidth(75)
                        min_edit.setObjectName(f"AVR_{model_name}_{param_name}_min")

                        # col 3: dấu gạch ngang giữa min-max
                        dash_label = QLabel("-")
                        dash_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

                        # col 4: max (Range đến)
                        max_edit = QtWidgets.QLineEdit(f"{ub:.4f}")
                        max_edit.setFixedWidth(75)
                        max_edit.setObjectName(f"AVR_{model_name}_{param_name}_max")

                        # Ẩn init/min/max sẵn, chỉ hiện khi tích checkbox
                        init_edit.hide()
                        min_edit.hide()
                        dash_label.hide()
                        max_edit.hide()

                        grid_layout.addWidget(param_checkbox, row_idx, 0)
                        grid_layout.addWidget(init_edit,      row_idx, 1)
                        grid_layout.addWidget(min_edit,       row_idx, 2)
                        grid_layout.addWidget(dash_label,     row_idx, 3)
                        grid_layout.addWidget(max_edit,       row_idx, 4)
                        # Connect checkbox: tích mới hiện Default và Range fields
                        param_checkbox.stateChanged.connect(
                            lambda state, ie=init_edit, mne=min_edit, dl=dash_label, mxe=max_edit:
                            [w.setVisible(state == QtCore.Qt.CheckState.Checked.value)
                            for w in (ie, mne, dl, mxe)]
                        )
                        # Store references
                        self.AVR_param_widgets[param_name] = {
                            'checkbox':  param_checkbox,
                            'initial':   initial,
                            'min':       lb,
                            'max':       ub,
                            'init_edit': init_edit,
                            'min_edit':  min_edit,
                            'max_edit':  max_edit,
                            'idx'     : idx
                        }

                    self.scroll_AVR_layout.addWidget(grid_widget)
                else:
                    self.scroll_AVR.hide()
                    self.groupBox_10.hide()
            else:
                self.scroll_AVR.hide()
                self.groupBox_10.hide()


    def on_GOV_check_changed(self, state):
            if state == QtCore.Qt.CheckState.Checked.value:
                self.GOV_list.show()
                self.GOV_label.show()
                self.GOV_select_all.show()
                current_model = self.GOV_list.currentText()
                if current_model:
                    self.on_GOV_model_changed(current_model)
            else:
                self.GOV_list.hide()
                self.GOV_label.hide()
                self.GOV_select_all.hide()
                self.groupBox_11.hide()
                self.scroll_GOV.hide()
                

    def on_GOV_model_changed(self, model_name):
            while self.scroll_GOV_layout.count():
                item = self.scroll_GOV_layout.takeAt(0)
                widget = item.widget()
                if widget:
                    widget.setParent(None)
            self.GOV_param_widgets = {}

            if not self.GOV_check.isChecked() or not model_name or model_name == "":
                self.groupBox_11.hide()
                self.scroll_GOV.hide()
                return
            
            model_data = self.load_json()
            gen_models = model_data.get('Model_dynamic', {}).get('GOV', {})

            if model_name in gen_models:
                params = gen_models[model_name]
                if params:
                    self.groupBox_11.show()
                    self.scroll_GOV.show()

                    grid_widget = QWidget()
                    grid_layout = QtWidgets.QGridLayout(grid_widget)
                    grid_layout.setContentsMargins(10, 5, 10, 5)
                    grid_layout.setHorizontalSpacing(8)
                    grid_layout.setVerticalSpacing(4)

                    header_default = QLabel("Default")
                    header_default.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                    header_range = QLabel("Range")
                    header_range.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                    grid_layout.addWidget(header_default, 0, 1)
                    grid_layout.addWidget(header_range,   0, 2, 1, 3)
                    for row_idx, (param_name, param_values) in enumerate(params.items(), start=1):
                        initial = param_values.get('initial', 0)
                        lb      = param_values.get('lb', 0)
                        ub      = param_values.get('ub', 100)
                        idx     = param_values.get('idx', 0)

                        param_checkbox = QtWidgets.QCheckBox(param_name)
                        param_checkbox.setObjectName(f"GOV_{model_name}_{param_name}")
                        # col 1: init (Default)
                        init_edit = QtWidgets.QLineEdit(f"{initial:.4f}")
                        init_edit.setFixedWidth(75)
                        init_edit.setObjectName(f"GOV_{model_name}_{param_name}_init")

                        # col 2: min (Range từ)
                        min_edit = QtWidgets.QLineEdit(f"{lb:.4f}")
                        min_edit.setFixedWidth(75)
                        min_edit.setObjectName(f"GOV_{model_name}_{param_name}_min")

                        # col 3: dấu gạch ngang giữa min-max
                        dash_label = QLabel("-")
                        dash_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

                        # col 4: max (Range đến)
                        max_edit = QtWidgets.QLineEdit(f"{ub:.4f}")
                        max_edit.setFixedWidth(75)
                        max_edit.setObjectName(f"GOV_{model_name}_{param_name}_max")

                        # Ẩn init/min/max sẵn, chỉ hiện khi tích checkbox
                        init_edit.hide()
                        min_edit.hide()
                        dash_label.hide()
                        max_edit.hide()

                        grid_layout.addWidget(param_checkbox, row_idx, 0)
                        grid_layout.addWidget(init_edit,      row_idx, 1)
                        grid_layout.addWidget(min_edit,       row_idx, 2)
                        grid_layout.addWidget(dash_label,     row_idx, 3)
                        grid_layout.addWidget(max_edit,       row_idx, 4)
                        # Connect checkbox: tích mới hiện Default và Range fields
                        param_checkbox.stateChanged.connect(
                            lambda state, ie=init_edit, mne=min_edit, dl=dash_label, mxe=max_edit:
                            [w.setVisible(state == QtCore.Qt.CheckState.Checked.value)
                            for w in (ie, mne, dl, mxe)]
                        )
                        # Store references
                        self.GOV_param_widgets[param_name] = {
                            'checkbox':  param_checkbox,
                            'initial':   initial,
                            'min':       lb,
                            'max':       ub,
                            'init_edit': init_edit,
                            'min_edit':  min_edit,
                            'max_edit':  max_edit,
                            'idx': idx
                        }

                    self.scroll_GOV_layout.addWidget(grid_widget)
                else:
                    self.scroll_GOV.hide()
                    self.groupBox_11.hide()
            else:
                self.scroll_GOV.hide()
                self.groupBox_11.hide()


    def on_PSS_check_changed(self, state):
            if state == QtCore.Qt.CheckState.Checked.value:
                self.PSS_list.show()
                self.PSS_label.show()
                self.PSS_select_all.show()
                current_model = self.PSS_list.currentText()
                if current_model:
                    self.on_PSS_model_changed(current_model)
            else:
                self.PSS_list.hide()
                self.PSS_label.hide()
                self.PSS_select_all.hide()
                self.groupBox_13.hide()
                self.scroll_PSS.hide()
                

    def on_PSS_model_changed(self, model_name):
            while self.scroll_PSS_layout.count():
                item = self.scroll_PSS_layout.takeAt(0)
                widget = item.widget()
                if widget:
                    widget.setParent(None)
            self.PSS_param_widgets = {}

            if not self.PSS_check.isChecked() or not model_name or model_name == "":
                self.groupBox_13.hide()
                self.scroll_PSS.hide()
                return
            
            model_data = self.load_json()
            gen_models = model_data.get('Model_dynamic', {}).get('PSS', {})

            if model_name in gen_models:
                params = gen_models[model_name]
                if params:
                    self.groupBox_13.show()
                    self.scroll_PSS.show()

                    grid_widget = QWidget()
                    grid_layout = QtWidgets.QGridLayout(grid_widget)
                    grid_layout.setContentsMargins(10, 5, 10, 5)
                    grid_layout.setHorizontalSpacing(8)
                    grid_layout.setVerticalSpacing(4)

                    header_default = QLabel("Default")
                    header_default.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                    header_range = QLabel("Range")
                    header_range.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                    grid_layout.addWidget(header_default, 0, 1)
                    grid_layout.addWidget(header_range,   0, 2, 1, 3)
                    for row_idx, (param_name, param_values) in enumerate(params.items(), start=1):
                        initial = param_values.get('initial', 0)
                        lb      = param_values.get('lb', 0)
                        ub      = param_values.get('ub', 100)
                        idx = param_values.get('idx', 0)

                        param_checkbox = QtWidgets.QCheckBox(param_name)
                        param_checkbox.setObjectName(f"PSS_{model_name}_{param_name}")
                        # col 1: init (Default)
                        init_edit = QtWidgets.QLineEdit(f"{initial:.4f}")
                        init_edit.setFixedWidth(75)
                        init_edit.setObjectName(f"PSS_{model_name}_{param_name}_init")

                        # col 2: min (Range từ)
                        min_edit = QtWidgets.QLineEdit(f"{lb:.4f}")
                        min_edit.setFixedWidth(75)
                        min_edit.setObjectName(f"PSS_{model_name}_{param_name}_min")

                        # col 3: dấu gạch ngang giữa min-max
                        dash_label = QLabel("-")
                        dash_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

                        # col 4: max (Range đến)
                        max_edit = QtWidgets.QLineEdit(f"{ub:.4f}")
                        max_edit.setFixedWidth(75)
                        max_edit.setObjectName(f"PSS_{model_name}_{param_name}_max")

                        # Ẩn init/min/max sẵn, chỉ hiện khi tích checkbox
                        init_edit.hide()
                        min_edit.hide()
                        dash_label.hide()
                        max_edit.hide()

                        grid_layout.addWidget(param_checkbox, row_idx, 0)
                        grid_layout.addWidget(init_edit,      row_idx, 1)
                        grid_layout.addWidget(min_edit,       row_idx, 2)
                        grid_layout.addWidget(dash_label,     row_idx, 3)
                        grid_layout.addWidget(max_edit,       row_idx, 4)
                        # Connect checkbox: tích mới hiện Default và Range fields
                        param_checkbox.stateChanged.connect(
                            lambda state, ie=init_edit, mne=min_edit, dl=dash_label, mxe=max_edit:
                            [w.setVisible(state == QtCore.Qt.CheckState.Checked.value)
                            for w in (ie, mne, dl, mxe)]
                        )
                        # Store references
                        self.PSS_param_widgets[param_name] = {
                            'checkbox':  param_checkbox,
                            'initial':   initial,
                            'min':       lb,
                            'max':       ub,
                            'init_edit': init_edit,
                            'min_edit':  min_edit,
                            'max_edit':  max_edit,
                            'idx': idx
                        }

                    self.scroll_PSS_layout.addWidget(grid_widget)
                else:
                    self.scroll_PSS.hide()
                    self.groupBox_13.hide()
            else:
                self.scroll_PSS.hide()
                self.groupBox_13.hide()


    def get_all_inputs(self):
        # 1. Lấy thông tin file hệ thống (Tab Input)
        selected_targets = []
        if self.ref_check_P.isChecked(): selected_targets.append("P")
        if self.ref_check_Q.isChecked(): selected_targets.append("Q")
        if self.ref_check_Vt.isChecked(): selected_targets.append("Vt")
        if self.ref_check_Ef.isChecked(): selected_targets.append("Ef")
        if self.ref_check_If.isChecked(): selected_targets.append("If")
        input_data = {
            "paths": {
                "sav_file": self.sav_text.text(),
                "dyr_file": self.dyr_text.text(),
                "out_file": self.out_text.text(),
                "ref_file": self.ref_text.text()
            },
            
            # 2. Thông số mô phỏng PSS/E (Tab PSSE Setting)
            "psse_setting": {
                "bus_id": self.Bus_id.text(),
                "gen_id": self.gen_id.text(),
                "sim_time": self.simulation_time.value(),
                "fault_time": self.time_fault.value(),
                "fault_step": self.step_fault.value(),
                "delt": float(self.DELT.text()) if self.DELT.text() else 0.01,
            },
            
            # 3. Thông số thuật toán PSO (Tab PSO Setting)
            "pso_params": {
                "iterations": self.iteration_2.value(),
                "particles": self.particle.value(),
                "c1": self.c1.value(),
                "c2": self.c2.value(),
                "wmax": self.wmax.value(),
                "wmin": self.wmin.value(),
                "tuning_target": selected_targets,
                "disturbance": self.disturbance.currentText()
            }
        }

        # 4. Lấy thông số các bộ điều khiển (GEN, AVR, GOV, PSS)
        # Ví dụ lấy thông số GEN nếu được tick chọn
        if self.GEN_check.isChecked():
            model_name = self.GEN_list.currentText()
            selected_params = {}
            for p_name, widgets in self.GEN_param_widgets.items():
                if widgets['checkbox'].isChecked():
                    selected_params[p_name] = {
                        "init": float(widgets['init_edit'].text()),
                        "min": float(widgets['min_edit'].text()),
                        "max": float(widgets['max_edit'].text()),
                        "idx": int(widgets['idx'])
                    }
            input_data["gen_model"] = {"model": model_name, "parameters": selected_params}
        if self.AVR_check.isChecked():
            model_name = self.AVR_list.currentText()
            selected_params = {}
            for p_name, widgets in self.AVR_param_widgets.items():
                if widgets['checkbox'].isChecked():
                    selected_params[p_name] = {
                        "init": float(widgets['init_edit'].text()),
                        "min": float(widgets['min_edit'].text()),
                        "max": float(widgets['max_edit'].text()),
                        "idx": int(widgets['idx'])
                    }
            input_data["avr_model"] = {"model": model_name, "parameters": selected_params}

        # Lấy thông số GOV nếu được tick chọn
        if self.GOV_check.isChecked():
            model_name = self.GOV_list.currentText()
            selected_params = {}
            for p_name, widgets in self.GOV_param_widgets.items():
                if widgets['checkbox'].isChecked():
                    selected_params[p_name] = {
                        "init": float(widgets['init_edit'].text()),
                        "min": float(widgets['min_edit'].text()),
                        "max": float(widgets['max_edit'].text()),
                        "idx": int(widgets['idx'])
                    }
            input_data["gov_model"] = {"model": model_name, "parameters": selected_params}

        # Lấy thông số PSS nếu được tick chọn
        if self.PSS_check.isChecked():
            model_name = self.PSS_list.currentText()
            selected_params = {}
            for p_name, widgets in self.PSS_param_widgets.items():
                if widgets['checkbox'].isChecked():
                    selected_params[p_name] = {
                        "init": float(widgets['init_edit'].text()),
                        "min": float(widgets['min_edit'].text()),
                        "max": float(widgets['max_edit'].text()),
                        "idx": int(widgets['idx'])
                    }
            input_data["pss_model"] = {"model": model_name, "parameters": selected_params}
        # Bạn có thể làm tương tự cho AVR, GOV, PSS...
        
        return input_data

    def setup_log_emitter(self):
        """Initialize the log emitter for thread-safe GUI updates"""
        self.log_emitter = LogEmitter()
        self.log_emitter.log_signal.connect(self._append_log)

    def _append_log(self, msg):
        """Slot to append log message to text edit (runs in main thread)"""
        self.log_output.append(msg)

    def run_py(self):
        from PSO_from_GUI import run_optimization, cancel_pso, reset_pso_flag
        all_input = self.get_all_inputs()
        self.log_output.clear()
        self.run.setEnabled(False)
        reset_pso_flag()

        # Initialize log emitter if not already done
        if not hasattr(self, 'log_emitter'):
            self.setup_log_emitter()

        def log_cb(msg):
            # Emit signal to update GUI from main thread (thread-safe)
            self.log_emitter.log_signal.emit(msg)

        def run_in_thread():
            try:
                run_optimization(all_input, log_cb=log_cb, do_plot=True, cancel_check_cb=cancel_pso)
            except KeyboardInterrupt:
                log_cb("\n<font color='red'><b>!!! ĐÃ HỦY QUÁ TRÌNH TỐI ƯU !!!</b></font>")
            except Exception as e:
                log_cb(f"\n<font color='red'><b>Lỗi: {e}</b></font>")
            finally:
                self.run.setEnabled(True)
                log_cb("\n<font color='green'><b>Hoàn tất!</b></font>")

        self.worker_thread = threading.Thread(target=run_in_thread, daemon=True)
        self.worker_thread.start()

    def on_GEN_select_all(self):
        """Select all GEN parameters"""
        for param_name, widgets in self.GEN_param_widgets.items():
            widgets['checkbox'].setChecked(True)

    def on_AVR_select_all(self):
        """Select all AVR parameters"""
        for param_name, widgets in self.AVR_param_widgets.items():
            widgets['checkbox'].setChecked(True)

    def on_GOV_select_all(self):
        """Select all GOV parameters"""
        for param_name, widgets in self.GOV_param_widgets.items():
            widgets['checkbox'].setChecked(True)

    def on_PSS_select_all(self):
        """Select all PSS parameters"""
        for param_name, widgets in self.PSS_param_widgets.items():
            widgets['checkbox'].setChecked(True)

    def stop(self):
        from PSO_from_GUI import cancel_pso
        cancel_pso()
        self.log_output.append("\n<font color='red'><b>!!! ĐANG HỦY QUÁ TRÌNH TỐI ƯU... !!!</b></font>")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Công cụ tối ưu PSO"))
        self.groupBox.setTitle(_translate("MainWindow", "INPUT"))
        self.label_2.setText(_translate("MainWindow", "sav_file"))
        self.sav.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "dyr_file"))
        self.dyr.setText(_translate("MainWindow", "..."))
        self.label_27.setText(_translate("MainWindow", "out_file"))
        self.out.setText(_translate("MainWindow", "..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "MESSENGER LOG"))
        self.run.setText(_translate("MainWindow", "RUN"))
        self.pushButton_2.setText(_translate("MainWindow", "HELP"))
        self.cancel.setText(_translate("MainWindow", "CANCEL"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab), _translate("MainWindow", "Input"))
        self.groupBox_3.setTitle(_translate("MainWindow", "PSSE Setting"))
        self.groupBox_4.setTitle(_translate("MainWindow", "PSSE Setting"))
        self.label_4.setText(_translate("MainWindow", "Bus:"))
        self.label_5.setText(_translate("MainWindow", "Simulation Time:"))
        self.label_6.setText(_translate("MainWindow", "Time fault:"))
        self.label_7.setText(_translate("MainWindow", "ID:"))
        self.label_12.setText(_translate("MainWindow", "Step fault:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Dynamic parameters"))
        self.checkBox.setText(_translate("MainWindow", "Network Solution"))
        self.label_13.setText(_translate("MainWindow", "iterations:"))
        self.label_14.setText(_translate("MainWindow", "Tolerance:"))
        self.label_15.setText(_translate("MainWindow", "DELT:"))
        self.label_16.setText(_translate("MainWindow", "Freq.Filter:"))
        self.checkBox_3.setText(_translate("MainWindow", "Simulation prameter"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Convert"))
        self.checkBox_2.setText(_translate("MainWindow", "LOAD"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Active Power"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Reactive Power"))
        self.label_17.setText(_translate("MainWindow", "% Contant Current"))
        self.label_18.setText(_translate("MainWindow", "%Constant Admittance"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_2), _translate("MainWindow", "PSSE Setting"))
        self.PSO_box.setTitle(_translate("MainWindow", "PSO parameter"))
        self.label_11.setText(_translate("MainWindow", "Num iteration:"))
        self.label_19.setText(_translate("MainWindow", "Num particles:"))
        self.label_20.setText(_translate("MainWindow", "c1:"))
        self.label_21.setText(_translate("MainWindow", "c2:"))
        self.label_22.setText(_translate("MainWindow", "wmax:"))
        self.label_28.setText(_translate("MainWindow", "wmin:"))
        self.REF_box.setTitle(_translate("MainWindow", "REF"))
        self.ref.setText(_translate("MainWindow", "..."))
        self.label_9.setText(_translate("MainWindow", "Tuning theo duong do thi "))


        self.ref_check_P.setText(_translate("MainWindow", "P"))
        self.ref_check_Q.setText(_translate("MainWindow", "Q"))
        self.ref_check_Vt.setText(_translate("MainWindow", "Vt"))
        self.ref_check_Ef.setText(_translate("MainWindow", "Ef"))
        self.ref_check_If.setText(_translate("MainWindow", "If"))

        self.label_10.setText(_translate("MainWindow", "Select"))
        self.label_8.setText(_translate("MainWindow", "ref_file"))
        self.label_43.setText(_translate("MainWindow", "Disturbance"))
        self.disturbance.setItemText(0, _translate("MainWindow", "No load"))
        self.disturbance.setItemText(1, _translate("MainWindow", "step respone"))
        self.disturbance.setItemText(2, _translate("MainWindow", "impulse"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_4), _translate("MainWindow", "PSO Setting"))
        self.GEN_check.setText(_translate("MainWindow", "GEN"))
        self.label_23.setText(_translate("MainWindow", "Thong so GEN"))
        self.GEN_list.setItemText(0, _translate("MainWindow", "GENROU"))
        self.GEN_list.setItemText(1, _translate("MainWindow", "GENSAL"))
        self.GEN_label.setText(_translate("MainWindow", "GEN Model"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Pamrameter GEN"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_Gen), _translate("MainWindow", "GEN"))
        self.label_29.setText(_translate("MainWindow", "Thong so AVR"))
        self.AVR_label.setText(_translate("MainWindow", "AVR Model"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Pamrameter GEN"))
        self.AVR_check.setText(_translate("MainWindow", "AVR"))
        self.AVR_list.setItemText(0, _translate("MainWindow", "ST6B"))
        self.AVR_list.setItemText(1, _translate("MainWindow", "DC1A"))
        self.AVR_list.setItemText(2, _translate("MainWindow", "SEXS"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_AVR), _translate("MainWindow", "AVR"))
        self.GOV_list.setItemText(0, _translate("MainWindow", "IEESGO"))
        self.GOV_check.setText(_translate("MainWindow", "GOV"))
        self.GOV_label.setText(_translate("MainWindow", "GOV Model"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Pamrameter GEN"))
        self.label_38.setText(_translate("MainWindow", "Thong so GOV"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_GOV), _translate("MainWindow", "GOV"))
        self.label_39.setText(_translate("MainWindow", "Thong so PSS"))
        self.PSS_label.setText(_translate("MainWindow", "PSS Model"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Pamrameter GEN"))
        self.PSS_check.setText(_translate("MainWindow", "PSS"))
        self.PSS_list.setItemText(0, _translate("MainWindow", "PSS2B"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_PSS), _translate("MainWindow", "PSS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
